complete -c anonsurf -l json -d 'Print daemon JSON without human formatting'
complete -c anonsurf -f -n '__fish_use_subcommand' -a start -d 'Start private Tor routing'
complete -c anonsurf -f -n '__fish_use_subcommand' -a stop -d 'Stop routing and restore managed networking'
complete -c anonsurf -f -n '__fish_use_subcommand' -a restart -d 'Restart routing'
complete -c anonsurf -f -n '__fish_use_subcommand' -a status -d 'Show daemon status'
complete -c anonsurf -f -n '__fish_use_subcommand' -a changeid -d 'Legacy alias for new-identity'
complete -c anonsurf -f -n '__fish_use_subcommand' -a new-identity -d 'Request Tor NEWNYM'
complete -c anonsurf -f -n '__fish_use_subcommand' -a myip -d 'Legacy alias for tor-check'
complete -c anonsurf -f -n '__fish_use_subcommand' -a tor-check -d 'Check Tor exit IP'
complete -c anonsurf -f -n '__fish_use_subcommand' -a repair -d 'Conservatively repair networking'
complete -c anonsurf -f -n '__fish_use_subcommand' -a logs -d 'Show daemon logs'
complete -c anonsurf -f -n '__fish_use_subcommand' -a doctor -d 'Check local dependencies'
complete -c anonsurf -f -n '__fish_use_subcommand' -a completions -d 'Print shell completions'
complete -c anonsurf -f -n '__fish_use_subcommand' -a config -d 'Manage configuration'
complete -c anonsurf -f -n '__fish_seen_subcommand_from config' -a 'show-default apply-default apply-file help'
complete -c anonsurf -f -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish'
